project_name: teldrive
env:
  - GO111MODULE=on

before:
  hooks:
  - make pre-ui
  - make ui
builds:
  - env:
      - CGO_ENABLED=0
    
    main: cmd/teldrive/main.go
    flags: -trimpath
    ldflags: "-extldflags -static -s -w"
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*.md
      - LICENSE