version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive/server
    restart: always
    container_name: teldrive
    volumes:
      - ./teldrive.db:/app/teldrive.db:rw
      - ./logs:/app/logs:rw
    env_file: teldrive.env
    ports:
      - 8080:8080
